version: '3'
services:
  node:
    restart: always
    build: .
    environment:
      - DATABASE_URL=mongodb://mongo:27017/BSUMagicPlan
      - PORT=3000
    ports:
      - 80:3000
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  web:
    restart: always
    image: justuskl/revit_converter:latest
    ports:
      - 3000:8080
