GET https://cloud.magic-plan.com/api/v2/workgroups/plans?sort=Plans.update_date&direction=desc&page=1
accecpt: application/json
key: dd0c7925689fbf4f2083412497c30f9d2445
customer: 5c7ef0e0b4132

###

GET https://cloud.magic-plan.com/api/v2/workgroups/plans/get/60a389c954e48
accecpt: application/json
key: dd0c7925689fbf4f2083412497c30f9d2445
customer: 5c7ef0e0b4132
    